// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TimeConfig$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TimeConfig";
  readonly sourceName: "contractweb3/TimeConfig.sol";
  readonly abi: [{"inputs":[],"name":"BTC_150K_BETTING_CLOSE","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"BTC_150K_PREDICTION_END","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x609c610033600b8282823980515f1a607314602757634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c8063c84bb35a146040578063e46d260014605c575b5f80fd5b604a636918db8481565b60405190815260200160405180910390f35b604a63695580848156fea2646970667358221220590b03cfb2f835c218fd6230b578c77359c60830ece1b8edb11b9935bad9014f64736f6c63430008180033";
  readonly deployedBytecode: "0x7300000000000000000000000000000000000000003014608060405260043610603c575f3560e01c8063c84bb35a146040578063e46d260014605c575b5f80fd5b604a636918db8481565b60405190815260200160405180910390f35b604a63695580848156fea2646970667358221220590b03cfb2f835c218fd6230b578c77359c60830ece1b8edb11b9935bad9014f64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contractweb3/TimeConfig.sol";
  readonly buildInfoId: "solc-0_8_24-77b4fcd3bf59b6b13780e9eb2d36ddd1fffd05c4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TimeConfig"]: TimeConfig$Type;
    ["contractweb3/TimeConfig.sol:TimeConfig"]: TimeConfig$Type;
  }
}