/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PredictionPoolInterface extends Interface {
    getFunction(nameOrSignature: "BASIS_POINTS" | "FEE_PERCENTAGE" | "FEE_WALLET" | "bettors" | "canClaimRefund" | "cancelPool" | "cancelled" | "category" | "claimRefund" | "claimWinnings" | "closePool" | "closingBid" | "closingDate" | "collectFees" | "description" | "emergencyResolve" | "emergencyStop" | "factory" | "getBettors" | "getFeeInfo" | "getLosingPot" | "getPoolStats" | "getWinnerPot" | "hasClaimed" | "isBettingOpen" | "isClosed" | "owner" | "placeBet" | "renounceOwnership" | "setEmergencyStop" | "setWinner" | "title" | "totalBets" | "totalClaimed" | "totalNo" | "totalYes" | "transferOwnership" | "userBets" | "winner" | "winnerSet"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetPlaced" | "EmergencyStopToggled" | "FeeTransferred" | "OwnershipTransferred" | "PoolCancelled" | "RefundClaimed" | "RewardClaimed" | "WinnerSet"): EventFragment;

    encodeFunctionData(functionFragment: 'BASIS_POINTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_PERCENTAGE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_WALLET', values?: undefined): string;
encodeFunctionData(functionFragment: 'bettors', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'canClaimRefund', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelPool', values: [string]): string;
encodeFunctionData(functionFragment: 'cancelled', values?: undefined): string;
encodeFunctionData(functionFragment: 'category', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimRefund', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimWinnings', values?: undefined): string;
encodeFunctionData(functionFragment: 'closePool', values?: undefined): string;
encodeFunctionData(functionFragment: 'closingBid', values?: undefined): string;
encodeFunctionData(functionFragment: 'closingDate', values?: undefined): string;
encodeFunctionData(functionFragment: 'collectFees', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'description', values?: undefined): string;
encodeFunctionData(functionFragment: 'emergencyResolve', values: [boolean, string]): string;
encodeFunctionData(functionFragment: 'emergencyStop', values?: undefined): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBettors', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFeeInfo', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLosingPot', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPoolStats', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWinnerPot', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasClaimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isBettingOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'isClosed', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [boolean]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setEmergencyStop', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setWinner', values: [boolean]): string;
encodeFunctionData(functionFragment: 'title', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalBets', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalClaimed', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalNo', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalYes', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userBets', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'winner', values?: undefined): string;
encodeFunctionData(functionFragment: 'winnerSet', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BASIS_POINTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_PERCENTAGE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_WALLET', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bettors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'canClaimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'category', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimWinnings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closePool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closingBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closingDate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collectFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'description', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyResolve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyStop', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBettors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFeeInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLosingPot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWinnerPot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isBettingOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isClosed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEmergencyStop', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWinner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'title', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalNo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalYes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userBets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'winnerSet', data: BytesLike): Result;
  }

  
    export namespace BetPlacedEvent {
      export type InputTuple = [bettor: AddressLike, amount: BigNumberish, choice: boolean, totalYes: BigNumberish, totalNo: BigNumberish, predictionTitle: string, userChoice: string];
      export type OutputTuple = [bettor: string, amount: bigint, choice: boolean, totalYes: bigint, totalNo: bigint, predictionTitle: string, userChoice: string];
      export interface OutputObject {bettor: string, amount: bigint, choice: boolean, totalYes: bigint, totalNo: bigint, predictionTitle: string, userChoice: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyStopToggledEvent {
      export type InputTuple = [stopped: boolean];
      export type OutputTuple = [stopped: boolean];
      export interface OutputObject {stopped: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeTransferredEvent {
      export type InputTuple = [feeWallet: AddressLike, amount: BigNumberish];
      export type OutputTuple = [feeWallet: string, amount: bigint];
      export interface OutputObject {feeWallet: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PoolCancelledEvent {
      export type InputTuple = [reason: string];
      export type OutputTuple = [reason: string];
      export interface OutputObject {reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundClaimedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint];
      export interface OutputObject {user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardClaimedEvent {
      export type InputTuple = [winner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [winner: string, amount: bigint];
      export interface OutputObject {winner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WinnerSetEvent {
      export type InputTuple = [winnerChoice: boolean, reason: string];
      export type OutputTuple = [winnerChoice: boolean, reason: string];
      export interface OutputObject {winnerChoice: boolean, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionPool;
    waitForDeployment(): Promise<this>;

    interface: PredictionPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASIS_POINTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_PERCENTAGE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_WALLET: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    bettors: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    canClaimRefund: TypedContractMethod<
      [_user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    cancelPool: TypedContractMethod<
      [_reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    cancelled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    category: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    claimRefund: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimWinnings: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    closePool: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    closingBid: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    closingDate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    collectFees: TypedContractMethod<
      [_claimAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    description: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    emergencyResolve: TypedContractMethod<
      [_winner: boolean, _reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyStop: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getBettors: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getFeeInfo: TypedContractMethod<
      [],
      [[string, bigint, bigint, boolean] & {_feeWallet: string, _feePercentage: bigint, _totalFees: bigint, _feesClaimed: boolean }],
      'view'
    >
    

    
    getLosingPot: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPoolStats: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {_totalYes: bigint, _totalNo: bigint, _totalBets: bigint, _bettorCount: bigint, _isClosed: boolean, _winnerSet: boolean, _cancelled: boolean }],
      'view'
    >
    

    
    getWinnerPot: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    hasClaimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isBettingOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isClosed: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [_choice: boolean, ],
      [void],
      'payable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setEmergencyStop: TypedContractMethod<
      [_stop: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setWinner: TypedContractMethod<
      [_winner: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    title: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalBets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalClaimed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalNo: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalYes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userBets: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, boolean, bigint] & {choice: boolean, amount: bigint, claimed: boolean, timestamp: bigint }],
      'view'
    >
    

    
    winner: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    winnerSet: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASIS_POINTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_PERCENTAGE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_WALLET'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'bettors'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'canClaimRefund'): TypedContractMethod<
      [_user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'cancelPool'): TypedContractMethod<
      [_reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'category'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'claimRefund'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimWinnings'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closePool'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closingBid'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'closingDate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'collectFees'): TypedContractMethod<
      [_claimAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'description'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyResolve'): TypedContractMethod<
      [_winner: boolean, _reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyStop'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBettors'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getFeeInfo'): TypedContractMethod<
      [],
      [[string, bigint, bigint, boolean] & {_feeWallet: string, _feePercentage: bigint, _totalFees: bigint, _feesClaimed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getLosingPot'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPoolStats'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {_totalYes: bigint, _totalNo: bigint, _totalBets: bigint, _bettorCount: bigint, _isClosed: boolean, _winnerSet: boolean, _cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getWinnerPot'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasClaimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isBettingOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isClosed'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [_choice: boolean, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEmergencyStop'): TypedContractMethod<
      [_stop: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWinner'): TypedContractMethod<
      [_winner: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'title'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalBets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalClaimed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalNo'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalYes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userBets'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, bigint, boolean, bigint] & {choice: boolean, amount: bigint, claimed: boolean, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'winner'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'winnerSet'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'BetPlaced'): TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
getEvent(key: 'EmergencyStopToggled'): TypedContractEvent<EmergencyStopToggledEvent.InputTuple, EmergencyStopToggledEvent.OutputTuple, EmergencyStopToggledEvent.OutputObject>;
getEvent(key: 'FeeTransferred'): TypedContractEvent<FeeTransferredEvent.InputTuple, FeeTransferredEvent.OutputTuple, FeeTransferredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PoolCancelled'): TypedContractEvent<PoolCancelledEvent.InputTuple, PoolCancelledEvent.OutputTuple, PoolCancelledEvent.OutputObject>;
getEvent(key: 'RefundClaimed'): TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
getEvent(key: 'RewardClaimed'): TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
getEvent(key: 'WinnerSet'): TypedContractEvent<WinnerSetEvent.InputTuple, WinnerSetEvent.OutputTuple, WinnerSetEvent.OutputObject>;

    filters: {
      
      'BetPlaced(address,uint256,bool,uint256,uint256,string,string)': TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
      BetPlaced: TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
    

      'EmergencyStopToggled(bool)': TypedContractEvent<EmergencyStopToggledEvent.InputTuple, EmergencyStopToggledEvent.OutputTuple, EmergencyStopToggledEvent.OutputObject>;
      EmergencyStopToggled: TypedContractEvent<EmergencyStopToggledEvent.InputTuple, EmergencyStopToggledEvent.OutputTuple, EmergencyStopToggledEvent.OutputObject>;
    

      'FeeTransferred(address,uint256)': TypedContractEvent<FeeTransferredEvent.InputTuple, FeeTransferredEvent.OutputTuple, FeeTransferredEvent.OutputObject>;
      FeeTransferred: TypedContractEvent<FeeTransferredEvent.InputTuple, FeeTransferredEvent.OutputTuple, FeeTransferredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PoolCancelled(string)': TypedContractEvent<PoolCancelledEvent.InputTuple, PoolCancelledEvent.OutputTuple, PoolCancelledEvent.OutputObject>;
      PoolCancelled: TypedContractEvent<PoolCancelledEvent.InputTuple, PoolCancelledEvent.OutputTuple, PoolCancelledEvent.OutputObject>;
    

      'RefundClaimed(address,uint256)': TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
      RefundClaimed: TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
    

      'RewardClaimed(address,uint256)': TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
      RewardClaimed: TypedContractEvent<RewardClaimedEvent.InputTuple, RewardClaimedEvent.OutputTuple, RewardClaimedEvent.OutputObject>;
    

      'WinnerSet(bool,string)': TypedContractEvent<WinnerSetEvent.InputTuple, WinnerSetEvent.OutputTuple, WinnerSetEvent.OutputObject>;
      WinnerSet: TypedContractEvent<WinnerSetEvent.InputTuple, WinnerSetEvent.OutputTuple, WinnerSetEvent.OutputObject>;
    
    };
  }