/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BellaNapoliPredictionFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BellaNapoliPredictionFactory__factory>
getContractFactory(name: 'BellaNapoliPredictionFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BellaNapoliPredictionFactory__factory>
getContractFactory(name: 'PredictionPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionPool__factory>
getContractFactory(name: 'PredictionPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionPool__factory>
getContractFactory(name: 'SimpleStorage', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SimpleStorage__factory>
getContractFactory(name: 'TimeConfig', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TimeConfig__factory>
getContractFactory(name: 'BellaNapoliPredictionFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BellaNapoliPredictionFactory__factory>
getContractFactory(name: 'PredictionPool', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionPool__factory>

  getContractAt(name: 'BellaNapoliPredictionFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BellaNapoliPredictionFactory>
getContractAt(name: 'BellaNapoliPredictionFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BellaNapoliPredictionFactory>
getContractAt(name: 'PredictionPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionPool>
getContractAt(name: 'PredictionPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionPool>
getContractAt(name: 'SimpleStorage', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SimpleStorage>
getContractAt(name: 'TimeConfig', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TimeConfig>
getContractAt(name: 'BellaNapoliPredictionFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BellaNapoliPredictionFactory>
getContractAt(name: 'PredictionPool', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionPool>

  deployContract(name: 'BellaNapoliPredictionFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BellaNapoliPredictionFactory>
deployContract(name: 'BellaNapoliPredictionFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BellaNapoliPredictionFactory>
deployContract(name: 'PredictionPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionPool>
deployContract(name: 'PredictionPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionPool>
deployContract(name: 'SimpleStorage', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleStorage>
deployContract(name: 'TimeConfig', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TimeConfig>
deployContract(name: 'BellaNapoliPredictionFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BellaNapoliPredictionFactory>
deployContract(name: 'PredictionPool', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionPool>

  deployContract(name: 'BellaNapoliPredictionFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BellaNapoliPredictionFactory>
deployContract(name: 'BellaNapoliPredictionFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BellaNapoliPredictionFactory>
deployContract(name: 'PredictionPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionPool>
deployContract(name: 'PredictionPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionPool>
deployContract(name: 'SimpleStorage', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SimpleStorage>
deployContract(name: 'TimeConfig', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TimeConfig>
deployContract(name: 'BellaNapoliPredictionFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BellaNapoliPredictionFactory>
deployContract(name: 'PredictionPool', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionPool>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  