/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bellaNapoliPredictionFactoryOptimizedSol from './BellaNapoliPredictionFactoryOptimized.sol/index.js';
export type { bellaNapoliPredictionFactoryOptimizedSol };
import type * as factoryUltraOptimizedSol from './factory-ultra-optimized.sol/index.js';
export type { factoryUltraOptimizedSol };
export type { BellaNapoliPredictionFactory } from './BellaNapoliPredictionFactory.js';
export type { PredictionPool } from './PredictionPool.js';
export type { SimpleStorage } from './SimpleStorage.js';
export type { TimeConfig } from './TimeConfig.js';
export * as factories from './factories/index.js';
export { BellaNapoliPredictionFactory__factory } from './factories/BellaNapoliPredictionFactory__factory.js';
export type { PredictionPool } from './BellaNapoliPredictionFactoryOptimized.sol/PredictionPool.js';
export { PredictionPool__factory } from './factories/BellaNapoliPredictionFactoryOptimized.sol/PredictionPool__factory.js';
export { SimpleStorage__factory } from './factories/SimpleStorage__factory.js';
export { TimeConfig__factory } from './factories/TimeConfig__factory.js';