/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TimeConfigInterface extends Interface {
    getFunction(nameOrSignature: "BTC_150K_BETTING_CLOSE" | "BTC_150K_PREDICTION_END"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'BTC_150K_BETTING_CLOSE', values?: undefined): string;
encodeFunctionData(functionFragment: 'BTC_150K_PREDICTION_END', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BTC_150K_BETTING_CLOSE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BTC_150K_PREDICTION_END', data: BytesLike): Result;
  }

  

  export interface TimeConfig extends BaseContract {
    
    connect(runner?: ContractRunner | null): TimeConfig;
    waitForDeployment(): Promise<this>;

    interface: TimeConfigInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BTC_150K_BETTING_CLOSE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BTC_150K_PREDICTION_END: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BTC_150K_BETTING_CLOSE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BTC_150K_PREDICTION_END'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }