/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bellaNapoliPredictionFactoryOptimizedSol from './BellaNapoliPredictionFactoryOptimized.sol/index.js';
export * as factoryUltraOptimizedSol from './factory-ultra-optimized.sol/index.js';
export { BellaNapoliPredictionFactory__factory } from './BellaNapoliPredictionFactory__factory.js';
export { PredictionPool__factory } from './PredictionPool__factory.js';
export { SimpleStorage__factory } from './SimpleStorage__factory.js';
export { TimeConfig__factory } from './TimeConfig__factory.js';