// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SimpleStorage$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SimpleStorage";
  readonly sourceName: "contractweb3/SimpleStorage.sol";
  readonly abi: [{"inputs":[],"name":"get","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"x","type":"uint256"}],"name":"set","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f80fd5b5060a58061001b5f395ff3fe6080604052348015600e575f80fd5b50600436106030575f3560e01c806360fe47b11460345780636d4ce63c146045575b5f80fd5b6043603f3660046059565b5f55565b005b5f5460405190815260200160405180910390f35b5f602082840312156068575f80fd5b503591905056fea2646970667358221220744a93f1c847d0c1269acb103e98eda0d0473b867577efdb2e47658ea0d4d96e64736f6c63430008180033";
  readonly deployedBytecode: "0x6080604052348015600e575f80fd5b50600436106030575f3560e01c806360fe47b11460345780636d4ce63c146045575b5f80fd5b6043603f3660046059565b5f55565b005b5f5460405190815260200160405180910390f35b5f602082840312156068575f80fd5b503591905056fea2646970667358221220744a93f1c847d0c1269acb103e98eda0d0473b867577efdb2e47658ea0d4d96e64736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contractweb3/SimpleStorage.sol";
  readonly buildInfoId: "solc-0_8_24-77b4fcd3bf59b6b13780e9eb2d36ddd1fffd05c4";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SimpleStorage"]: SimpleStorage$Type;
    ["contractweb3/SimpleStorage.sol:SimpleStorage"]: SimpleStorage$Type;
  }
}